# test notebook for stella ZAMS calc code

In [1]:
# imports
import numpy as np
from scipy.optimize import least_squares

# constants
import constants as c
from scipy.constants import N_A

# plotting
import matplotlib.pyplot as plt
import seaborn as sb
plt.style.use('default')
sb.set_context("talk")
plt.rcParams['font.family'] = 'monospace'   # Fonts
plt.rcParams['font.monospace'] = 'DejaVu Sans Mono'

In [2]:
import interpolate
import energy
import density
from guesses import *
from ode import ode
from shootf import shooter, solver

In [3]:
# surface
M_star = 1.67*c.Ms
L_star = (M_star/c.Ms)**(3.5)*c.Ls # eq. 1.88 HKT
R_star = (M_star/c.Ms)**(0.75)*c.Rs # eq. 1.87 HKT
# core
Pc = (3/(8*np.pi))*(c.G*(M_star)**2)/(R_star)**4 # constant density sphere, lower limit!
Tc = (1/2)*((4/(3+5*0.7))/(N_A*c.k))*(c.G*M_star)/(R_star) # constant density sphere
# guess to inflate constant density sphere pressure
P_factor = 1e1
Pc *= P_factor
# initial guess vector
vec = np.array([L_star, Pc, R_star, Tc])
# shootf args
args = (M_star, 0.33, int(1e5), 1e-12, 0.9999, True)
# set limits for the minimizer
bounds = ([L_star*1e-1,Pc,R_star*1e-1,Tc], [L_star*1e1, Pc/P_factor*1e4, R_star*1e1, Tc*1e3])

In [ ]:
# todo, set x_scale for each variable to enable better tolerance estimate
final = least_squares(shooter, vec, args=args, bounds=bounds, 
                      method='dogbox', loss='arctan', 
                      gtol=1e-14, 
                      xtol=None, 
                      ftol=None, 
                      x_scale='jac',
                     )

2023-04-28 13:26:40,152	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.94474434 -5.95467623  0.22709195 -0.45595282]


2023-04-28 13:27:10,096	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.94474434 -5.95467632  0.22709195 -0.45595283]


2023-04-28 13:27:37,198	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.94474434 -5.95467614  0.22709195 -0.45595282]


2023-04-28 13:28:06,560	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.94474435 -5.95467599  0.22709195 -0.45595281]


2023-04-28 13:28:35,862	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.94474434 -5.95467622  0.22709195 -0.4559528 ]


2023-04-28 13:29:04,596	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.97334784 -3.12101751  0.16758445 -0.03144261]


2023-04-28 13:29:39,475	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.97334784 -3.12101757  0.16758445 -0.03144261]


2023-04-28 13:30:07,924	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.97334784 -3.12101746  0.16758445 -0.03144261]


2023-04-28 13:30:37,495	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.97334784 -3.12101737  0.16758445 -0.0314426 ]


2023-04-28 13:31:08,316	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.97334784 -3.1210175   0.16758445 -0.03144259]


2023-04-28 13:31:43,775	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99372172 -1.12481338  0.09358137 -0.08953406]


2023-04-28 13:32:11,196	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99372172 -1.12481356  0.09358137 -0.08953409]


2023-04-28 13:32:37,603	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99372172 -1.12481336  0.09358137 -0.08953406]


2023-04-28 13:33:10,526	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99372172 -1.12481302  0.09358136 -0.089534  ]


2023-04-28 13:33:39,900	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99372172 -1.12481338  0.09358137 -0.08953404]


2023-04-28 13:34:06,073	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99475269 -0.87829101  0.08214288 -0.05159733]


2023-04-28 13:34:37,759	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99475269 -0.87829111  0.08214288 -0.05159735]


2023-04-28 13:35:06,896	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99475269 -0.87829099  0.08214287 -0.05159733]


2023-04-28 13:35:37,305	INFO worker.py:1553 -- Started a local Ray instance.


solved inner
solved exterior
[-0.99475269 -0.8782909   0.08214287 -0.05159731]


2023-04-28 13:36:10,965	INFO worker.py:1553 -- Started a local Ray instance.


In [ ]:
final

In [ ]:
if np.sum(final.active_mask**2) != 0:
    print('something ran up against a bound')

In [ ]:
solution = solver(final.x, M_star=args[0], M_fit=args[1], n=1e6, in_factor=args[3], out_factor=args[4], multithread=args[5])

In [ ]:
# what is an appropriate P_factor to speed up convergence?
print('ratio between constant density Pc and converged solution',solution[2].max()/(Pc/P_factor))

In [ ]:
print('ratio between constant density Tc and converged solution',solution[4].max()/Tc)

In [ ]:
with open('converged_interior_{}.npy'.format(M_star/c.Ms), 'wb') as f:
    np.save(f, solution)

In [ ]:
solution = np.load('converged_interior_{}.npy'.format(M_star/c.Ms))

In [ ]:
# a figure like 9.1 in HKT but in mass space, y-values near 1
plt.figure(figsize=(9,6))

plt.plot(solution[0]/M_star, solution[5]/solution[5].max(), color='cornflowerblue', label=r'$\rho~[g/cm^3]$'.format())
plt.plot(solution[0]/M_star, solution[2]/solution[2].max(), color='tomato', label=r'$P~[Ba]$')
plt.plot(solution[0]/M_star, solution[4]/solution[4].max(), color='xkcd:forest green', label=r'$T~[K]$')
plt.plot(solution[0]/M_star, solution[1]/solution[1].max(), color='xkcd:lavender', label=r'$L~[erg/s]$')

plt.xlabel(r'M$_\mathrm{r}$ [M$_\star$]')
plt.ylabel(r'Normalized Quantity')
plt.legend(fontsize=13, bbox_to_anchor=(0.55,0.5))
plt.xlim(-0.1,1.1)
plt.minorticks_on()

plt.savefig('./figures/run_over_mass_{}.png'.format(M_star/c.Ms), dpi=300, bbox_inches='tight')

In [ ]:
# reproduce figure 9.1 in HKT but in mass space

plt.figure(figsize=(9,6))

plt.plot(solution[3]/R_star, solution[5]*1e5, color='cornflowerblue', label=r'$\log(\rho)\times10^5$ $[g/cm^3]$')
plt.plot(solution[3]/R_star, solution[2]*1e-8, color='tomato', label=r'$\log(P)\times10^{-8}$ $[Ba]$')
plt.plot(solution[3]/R_star, solution[4], color='xkcd:forest green', label=r'$\log(T)$ $[K]$')

plt.yscale('log')
plt.xlabel(r'R [R$_\star$]')
plt.ylabel(r'$\log(quantity)\times C$')
plt.legend(fontsize=10)
plt.ylim(1,1e10)
plt.xlim(0,1.1)

plt.savefig('./figures/run_over_radius_HKT9-1_{}.png'.format(M_star/c.Ms), dpi=300, bbox_inches='tight')

In [ ]:
plt.figure(figsize=(9,6))

plt.plot(solution[0]/M_star, solution[-1], color='cornflowerblue', label=r'$\nabla_{rad}$')
plt.plot(solution[0]/M_star, np.zeros_like(solution[0])+0.4, color='tomato', label=r'$\nabla_{ad}$')

# plt.yscale('log')
plt.xlabel(r'M [M$_\star$]')
plt.ylabel(r'$\nabla$ [K/cm]')
plt.legend()
# plt.ylim(1,1e10)
plt.xlim(-0.1,1.1)
plt.minorticks_on()
plt.savefig('./figures/del_over_mass_{}.png'.format(M_star/c.Ms), dpi=300, bbox_inches='tight')


In [ ]:
# central density vs avg density
converged_concentration = solution[5].max()/(4*np.pi*M_star/(3*R_star**3))

print("rho_c/rho_avg is", str(round(converged_concentration,2)))

In [ ]:
from scipy.integrate import solve_ivp

# compare to polytrope

def dtheta(xi, y, n):
    theta, psi = y
    return (psi, -np.power(theta, n) - 2 * psi / xi)

ns = np.linspace(0, 3.5, num=51) # a reasonable number of n for plotting
ts = np.logspace(np.log10(1e-15), np.log10(1000.), num=1000) # dense enough to look smooth

concentrations = np.zeros(ns.shape[0])
for i, n in enumerate(ns):
    soln = solve_ivp(dtheta, [1e-16, 1001.], [1., 0.], args=[n], t_eval=ts)
    # degree of central concentration
    concentration = 1/3 * (soln.t[np.argmin(np.abs(soln.y[0]))]/(-1*soln.y[1][np.argmin(np.abs(soln.y[0]))]))
#     print("for n={}, rho_c/rho_avg is".format(n), str(round(concentration,2)))
    concentrations[i] += concentration

x = ns
y = concentrations
    
points = np.array([x, y]).T.reshape(-1, 1, 2)
segments = np.concatenate([points[:-1], points[1:]], axis=1)

fig, axs = plt.subplots(1, 1, figsize=(9,5))

# Create a continuous norm to map from data points to colors
norm = plt.Normalize(x.min(), x.max())
from matplotlib.collections import LineCollection
lc = LineCollection(segments, cmap='magma', norm=norm)
# Set the values used for colormapping
lc.set_array(x)
lc.set_linewidth(2)
line = axs.add_collection(lc)
# cb = fig.colorbar(line, ax=axs)
# cb.ax.set_title('n')
plt.hlines(converged_concentration, 0, 3.5, ls='--', color='k')
plt.annotate('Model degree of \n central concentration', (2.3,5.5), fontsize=10)

plt.minorticks_on()
plt.ylim(1, 1e2)
plt.yscale('log')

plt.xlabel('Polytropic Index n')
plt.ylabel(r'$\rho_c~/~\left|\rho\right|}$')

plt.savefig('./figures/central_concentration_polytropes_{}.png'.format(M_star/c.Ms), dpi=300, bbox_inches='tight')